#### R Packages to Download ####

install.packages("devtools")
install.packages("ggplot2")
install.packages("GGally")
install.packages("ggfortify")
install.packages("ggmap")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("Lahman")
install.packages("RMySQL")
install.packages("car")
install.packages("MASS")
install.packages("rpart")
install.packages("corrplot")
install.packages("broom")
install.packages("rmarkdown")
install.packages("shiny")
install.packages("knitr")
install.packages("caret")
install.packages("RMSE")
install.packages("cvTools")
install.packages("installr")
install.packages("scales")
install.packages("rsconnect")
install.packages("ggthemes")
install.packages("plyr")
install.packages("fivethirtyeight")
devtools::install_github("keberwein/mlbgameday")
devtools::install_github("pitchRx", "cpsievert")
devtools::install_github("keberwein/baseballDBR")
devtools::install_github("BillPetti/baseballr")
devtools::install_github("keberwein/blscrapeR")
